-- MySQL 8.x - Script de carga para entorno local Windows
-- Ajustado a:
-- 1) Rutas absolutas con /
-- 2) LOAD DATA LOCAL INFILE
-- 3) Fechas ISO con 'T' y control de truncados
-- 4) Integridad referencial desactivada durante carga masiva

SET @OLD_SQL_MODE = @@sql_mode;
SET sql_mode = '';

SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

-- Carga tabla maestra (intervenciones)
LOAD DATA LOCAL INFILE 'C:/Users/luise/OneDrive/Desktop/LuisVillegas_PruebaTecnica_Oberstaff/.cursor/skills/muestras/vista_climasur_intervenciones.csv'
INTO TABLE intervenciones
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  COD_INCIDENCIA, NUM_INTERVENCION, ORDEN_SERVICIO, NUMERO_PEDIDO, COD_TIPO, TIPO, COD_SINTOMA, SINTOMA,
  COD_DEPARTAMENTO, DEPARTAMENTO, COD_ESTADO, ESTADO, COD_PRIORIDAD, PRIORIDAD, ES_CITA, @FECHA_INCIDENCIA_RAW,
  @FECHA_ASIGNACION_RAW, @HORA_ASIGNACION_RAW, @FECHA_FIN_ASIG_RAW, @HORA_FIN_ASIGNACION_RAW, @FECHA_FINALIZACION_RAW,
  COD_CLIENTE, CLIENTE, CIF, COD_AGENTE, NOMBRE_AGENTE, COD_SEDE, SEDE, DIRECCION_SEDE, LOCALIDAD_SEDE, CP_SEDE,
  PROVINCIA_SEDE, COD_RESPONSABLE, RESPONSABLE, COD_TECNICO, NOMBRE_TECNICO, CODIGOS_PERSONAL, NOMBRES_PERSONAL,
  TIPO_MANTENIMIENTO, VINCULADO_OBRA, VINCULADO_MANTENIMIENTO, AREALIZAR, NOTAS_INTERNAS, NOTAS_AVISO, A_REALIZAR,
  REALIZADO, REQ_INFORME, OBS_INFORME, REQ_PRESUPUESTO, OBS_PRESUPUESTO, DURACION_PLANIFICADA
)
SET
  FECHA_INCIDENCIA = IF(@FECHA_INCIDENCIA_RAW = '', NULL, STR_TO_DATE(@FECHA_INCIDENCIA_RAW, '%Y-%m-%dT%H:%i:%s')),
  FECHA_ASIGNACION = IF(@FECHA_ASIGNACION_RAW = '', NULL, STR_TO_DATE(@FECHA_ASIGNACION_RAW, '%Y-%m-%d')),
  HORA_ASIGNACION = IF(@HORA_ASIGNACION_RAW = '', NULL, STR_TO_DATE(@HORA_ASIGNACION_RAW, '%H:%i')),
  FECHA_FIN_ASIG = IF(@FECHA_FIN_ASIG_RAW = '', NULL, STR_TO_DATE(@FECHA_FIN_ASIG_RAW, '%Y-%m-%d')),
  HORA_FIN_ASIGNACION = IF(@HORA_FIN_ASIGNACION_RAW = '', NULL, STR_TO_DATE(@HORA_FIN_ASIGNACION_RAW, '%H:%i')),
  FECHA_FINALIZACION = IF(@FECHA_FINALIZACION_RAW = '', NULL, STR_TO_DATE(@FECHA_FINALIZACION_RAW, '%Y-%m-%dT%H:%i:%s'));

-- Carga horas imputadas
LOAD DATA LOCAL INFILE 'C:/Users/luise/OneDrive/Desktop/LuisVillegas_PruebaTecnica_Oberstaff/.cursor/skills/muestras/vista_climasur_intervenciones_horas.csv'
INTO TABLE intervenciones_horas
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  COD_MANO_OBRA, COD_INCIDENCIA, COD_USUARIO, USUARIO, @FECHA_INICIO_RAW, @FECHA_FIN_RAW,
  COD_CATEGORIA_MOBRA, CATEGORIA_MANO_OBRA, COSTE, VENTA
)
SET
  FECHA_INICIO = IF(@FECHA_INICIO_RAW = '', NULL, STR_TO_DATE(@FECHA_INICIO_RAW, '%Y-%m-%dT%H:%i:%s')),
  FECHA_FIN = IF(@FECHA_FIN_RAW = '', NULL, STR_TO_DATE(@FECHA_FIN_RAW, '%Y-%m-%dT%H:%i:%s'));

-- Carga materiales (PK tecnica auto_increment)
LOAD DATA LOCAL INFILE 'C:/Users/luise/OneDrive/Desktop/LuisVillegas_PruebaTecnica_Oberstaff/.cursor/skills/muestras/vista_climasur_intervenciones_materiales.csv'
INTO TABLE intervenciones_materiales
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  COD_INCIDENCIA, COD_USUARIO, USUARIO, COD_PIEZA, REFERENCIA, DESCRIPCION, MARCA, MODELO,
  UNIDADES, PRECIO_COSTE, PRECIO_VENTA, DESCUENTO
);

-- Carga desplazamientos
LOAD DATA LOCAL INFILE 'C:/Users/luise/OneDrive/Desktop/LuisVillegas_PruebaTecnica_Oberstaff/.cursor/skills/muestras/vista_climasur_desplazamientos.csv'
INTO TABLE desplazamientos
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  COD_DESPLAZAMIENTO, COD_INCIDENCIA, COD_OBRA, COD_ZONA, NOMBRE_ZONA, COD_USUARIO, USUARIO,
  PRECIO_COSTE, PRECIO_VENTA, @FECHA_HORA_RAW
)
SET
  FECHA_HORA = IF(@FECHA_HORA_RAW = '', NULL, STR_TO_DATE(@FECHA_HORA_RAW, '%Y-%m-%dT%H:%i:%s'));

SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET sql_mode = @OLD_SQL_MODE;

