-- MySQL 8.x
-- Objetivo: modelar las 4 vistas CSV con relaciones por COD_INCIDENCIA.
-- Nota de diseno:
-- 1) COD_INCIDENCIA se conserva como identificador de negocio (PK en intervenciones).
-- 2) horas y desplazamientos tienen identificadores claros en origen, se usan como PK naturales.
-- 3) materiales no trae identificador unico confiable por fila, por eso se agrega PK tecnica.

CREATE TABLE IF NOT EXISTS intervenciones (
  COD_INCIDENCIA BIGINT NOT NULL,
  NUM_INTERVENCION VARCHAR(50),
  ORDEN_SERVICIO VARCHAR(50),
  NUMERO_PEDIDO VARCHAR(50),
  COD_TIPO INT,
  TIPO VARCHAR(100),
  COD_SINTOMA INT,
  SINTOMA TEXT,
  COD_DEPARTAMENTO INT,
  DEPARTAMENTO VARCHAR(150),
  COD_ESTADO INT,
  ESTADO VARCHAR(50),
  COD_PRIORIDAD INT,
  PRIORIDAD VARCHAR(50),
  ES_CITA VARCHAR(10),
  FECHA_INCIDENCIA DATETIME,
  FECHA_ASIGNACION DATE,
  HORA_ASIGNACION TIME,
  FECHA_FIN_ASIG DATE,
  HORA_FIN_ASIGNACION TIME,
  FECHA_FINALIZACION DATETIME,
  COD_CLIENTE BIGINT,
  CLIENTE VARCHAR(255),
  CIF VARCHAR(40),
  COD_AGENTE BIGINT,
  NOMBRE_AGENTE VARCHAR(255),
  COD_SEDE BIGINT,
  SEDE VARCHAR(255),
  DIRECCION_SEDE TEXT,
  LOCALIDAD_SEDE VARCHAR(150),
  CP_SEDE VARCHAR(20),
  PROVINCIA_SEDE VARCHAR(100),
  COD_RESPONSABLE BIGINT,
  RESPONSABLE VARCHAR(255),
  COD_TECNICO BIGINT,
  NOMBRE_TECNICO VARCHAR(255),
  CODIGOS_PERSONAL TEXT,
  NOMBRES_PERSONAL TEXT,
  TIPO_MANTENIMIENTO VARCHAR(100),
  VINCULADO_OBRA VARCHAR(10),
  VINCULADO_MANTENIMIENTO VARCHAR(10),
  AREALIZAR TEXT,
  NOTAS_INTERNAS TEXT,
  NOTAS_AVISO TEXT,
  A_REALIZAR TEXT,
  REALIZADO TEXT,
  REQ_INFORME VARCHAR(10),
  OBS_INFORME TEXT,
  REQ_PRESUPUESTO VARCHAR(10),
  OBS_PRESUPUESTO TEXT,
  DURACION_PLANIFICADA VARCHAR(10),
  PRIMARY KEY (COD_INCIDENCIA)
);

CREATE TABLE IF NOT EXISTS intervenciones_horas (
  COD_MANO_OBRA BIGINT NOT NULL,
  COD_INCIDENCIA BIGINT NOT NULL,
  COD_USUARIO BIGINT,
  USUARIO VARCHAR(255),
  FECHA_INICIO DATETIME,
  FECHA_FIN DATETIME,
  COD_CATEGORIA_MOBRA INT,
  CATEGORIA_MANO_OBRA VARCHAR(100),
  COSTE DECIMAL(12,2),
  VENTA DECIMAL(12,2),
  PRIMARY KEY (COD_MANO_OBRA),
  CONSTRAINT fk_horas_incidencia
    FOREIGN KEY (COD_INCIDENCIA)
    REFERENCES intervenciones (COD_INCIDENCIA)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS intervenciones_materiales (
  ID_MATERIAL BIGINT NOT NULL AUTO_INCREMENT,
  COD_INCIDENCIA BIGINT NOT NULL,
  COD_USUARIO BIGINT,
  USUARIO VARCHAR(255),
  COD_PIEZA BIGINT,
  REFERENCIA VARCHAR(100),
  DESCRIPCION TEXT,
  MARCA VARCHAR(100),
  MODELO VARCHAR(100),
  UNIDADES DECIMAL(12,2),
  PRECIO_COSTE DECIMAL(12,2),
  PRECIO_VENTA DECIMAL(12,2),
  DESCUENTO DECIMAL(12,2),
  PRIMARY KEY (ID_MATERIAL),
  CONSTRAINT fk_materiales_incidencia
    FOREIGN KEY (COD_INCIDENCIA)
    REFERENCES intervenciones (COD_INCIDENCIA)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS desplazamientos (
  COD_DESPLAZAMIENTO BIGINT NOT NULL,
  COD_INCIDENCIA BIGINT NOT NULL,
  COD_OBRA BIGINT,
  COD_ZONA BIGINT,
  NOMBRE_ZONA VARCHAR(100),
  COD_USUARIO BIGINT,
  USUARIO VARCHAR(255),
  PRECIO_COSTE DECIMAL(12,2),
  PRECIO_VENTA DECIMAL(12,2),
  FECHA_HORA DATETIME,
  PRIMARY KEY (COD_DESPLAZAMIENTO),
  CONSTRAINT fk_desplazamientos_incidencia
    FOREIGN KEY (COD_INCIDENCIA)
    REFERENCES intervenciones (COD_INCIDENCIA)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX idx_horas_cod_incidencia ON intervenciones_horas (COD_INCIDENCIA);
CREATE INDEX idx_materiales_cod_incidencia ON intervenciones_materiales (COD_INCIDENCIA);
CREATE INDEX idx_desplazamientos_cod_incidencia ON desplazamientos (COD_INCIDENCIA);
